# Site settings
title: Metro PDX Soccer
description: "Portland 7v7 soccer league for men, women, and coed"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo:
    url: svg/min/logo.svg

# Hero
hero:
    hero_bg: bannerbg.jpg
    hero_img: banner.jpg
    hero_logo: logo.jpg
    hero_title: Metro PDX Soccer
    hero_description: A responsive Jekyll theme for dental clinics.

# Contact form
api_token: # Enter API token here

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 14
    address: 11999 Southeast Fuller Road, Milwaukie, OR 97222
    address_details: svg/min/logo.svg

# Social settings
social:
    # facebook: http://facebook.com
    # twitter: http://twitter.com
    # instagram: http://instagram.com
    # youtube: http://youtube.com
    # skype: skype:obaez_design?userinfo
    # feed: yes

# Footer
copyright: Â© 2016 MetroPDXSoccer - All rights reserved

# Build settings
markdown: kramdown

exclude:
    - package.json
    - Gruntfile.js
    - node_modules
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - .gitignore
    - README.md
    - LICENSE.md

# Theme Settings
analytics:
google_verification:

# Prose settings
prose:
    ignore:
        - _config.yml
        - /_layouts
        - /_includes
        - /_scss
        - /css
        - /js
        - /svg
        - /favicon
        - favicon.ico
        - package.json
        - Gruntfile.js
        - node_modules
        - .sass-cache
        - Gemfile
        - Gemfile.lock
        - .gitignore
        - README.md
        - LICENSE.md
        - CNAME
        - favicon.png
        - feed.xml
        - index.html

#   rooturl: '_posts'
#   siteurl: 'http://prose.github.io/starter/'
#   relativeLinks: 'http://prose.github.io/starter/links.jsonp'
#   media: 'media'
#   metadata:
#     _posts:
#       - name: "category"
#         field:
#           element: "hidden"
#           value: "blog"
#       - name: "layout"
#         field:
#           element: "hidden"
#           value: "blog"
#       - name: "title"
#         field:
#           element: "text"
#           label: "Title"
#           value: ""
#       - name: "splash"
#         field:
#           element: "text"
#           label: "Splash image"
#           value: ""
#       - name: "tags"
#         field:
#           element: "multiselect"
#           label: "Add Tags"
#           placeholder: "Choose Tags"
#           options:
#             - name: "Apples"
#               value: "apples"
#             - name: "Bananas"
#               value: "bananas"
#             - name: "Pears"
#               value: "pears"
#             - name: "Mangos"
#               value: "mangos"
#     _posts/static:
#       - name: "layout"
#         field:
#           element: "hidden"
#           value: "page"
#       - name: "title"
#         field:
#           element: "text"
#           label: "Title"
#           value: ""
#       - name: "permalink"
#         field:
#           element: "text"
#           label: "Permalink"
#           value: ""